name: index-create-from-file

on:
  workflow_dispatch:

jobs:
  create-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heyitsmemark/create-azure-search-index@main
        with:
          azureSearchInstance: plop
          azureSearchAdminKey: ${{ secrets.AZURE_SEARCH_ADMIN_KEY }}
          indexDefinitionFile: ./test-definitions/index.json